<a href="https://colab.research.google.com/github/viatorvii-cell/Mathworkshop/blob/main/workshop6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Qno 1

In [ ]:
import numpy as np

A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

print(A)
print("Shape:", A.shape)
print("Dimensions:", A.ndim)
print("Data type:", A.dtype)
print("Size:", A.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Dimensions: 2
Data type: int64
Size: 9


Qno 2

In [ ]:
A = np.ones((4,5)) * 3.0
print(A)

[[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]


Qno 3

In [ ]:
A = np.full((4,5), 3.0)
print(A)

[[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]


Qno 4

In [ ]:
A = np.zeros((3,3))

for i in range(3):
    for j in range(3):
        A[i,j] = 0.5 * abs(i - 3*j)

print(A)

[[0.  1.5 3. ]
 [0.5 1.  2.5]
 [1.  0.5 2. ]]


Qno 5

In [ ]:
A = np.diag([1,2,3,4])
print(A)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


Qno 6

In [ ]:
A = np.arange(20).reshape(4,5)
print("Original:\n", A)

B = A[:3, :3]
print("Sliced:\n", B)

Original:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
Sliced:
 [[ 0  1  2]
 [ 5  6  7]
 [10 11 12]]


Qno 7

In [ ]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

B = np.array([[1,1,1],
              [2,2,2]])

Qno 8

In [ ]:
def mat_vec_mult(A, x):
    result = []
    for i in range(len(A)):
        s = 0
        for j in range(len(x)):
            s += A[i][j] * x[j]
        result.append(s)
    return result

A = [[1,2,3],
     [4,5,6],
     [7,8,9]]

x = [1,1,1]

print("Manual:", mat_vec_mult(A,x))

A_np = np.array(A)
x_np = np.array(x)

print("NumPy:", A_np.dot(x_np))

Manual: [6, 15, 24]
NumPy: [ 6 15 24]


Qno 9

In [ ]:
def mat_mat_mult(A, B):
    result = [[0]*len(B[0]) for _ in range(len(A))]

    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                result[i][j] += A[i][k] * B[k][j]

    return result

A = [[1,2,3],
     [4,5,6]]

B = [[1,2],
     [3,4],
     [5,6]]

print("Manual:", mat_mat_mult(A,B))

A_np = np.array(A)
B_np = np.array(B)

print("NumPy:\n", A_np.dot(B_np))

Manual: [[22, 28], [49, 64]]
NumPy:
 [[22 28]
 [49 64]]


Qno 10

In [ ]:
def is_symmetric(A):
    A = np.array(A)
    return np.array_equal(A, A.T)

A = [[1,2,3],
     [2,5,6],
     [3,6,9]]

print(is_symmetric(A))

True
